Decouple encryption from allow action
aporeto-inc/trireme-lib pull request #497
Opened 2018-03-19 22:13 UTC by varks

This PR decouples encryption from allow action.

2018-03-19 23:50 UTC, varks commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "trireme-lib",
    "pr-id": "497",
    "commit-sha": "a167ffc2d435143bc5886496203bd61e810ab21c"
  },
  {
    "component": "enforcerd",
    "pr-id": "517",
    "commit-sha": "3ca6cf96a831bbd0d1fe0baef1962249c7c0e17d"
  }
]
```

2018-03-20 00:07 UTC, varks commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "trireme-lib",
    "pr-id": "497",
    "commit-sha": "a167ffc2d435143bc5886496203bd61e810ab21c"
  },
  {
    "component": "enforcerd",
    "pr-id": "517",
    "commit-sha": "894cd49427b0313f141079ca04164d9a0f11a3b6"
  }
]
```

2018-03-20 01:22 UTC, primalmotion commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "gaia",
    "pr-id": "118",
    "commit-sha": "e92f3849b53bc399304203ccdba37557937ea870"
  },
  {
    "component": "trireme-lib",
    "pr-id": "497",
    "commit-sha": "a167ffc2d435143bc5886496203bd61e810ab21c"
  },
  {
    "component": "squall",
    "pr-id": "337",
    "commit-sha": "376512f27219d5dc7f1576206b046d6ae6c0a25a"
  },
  {
    "component": "clad",
    "pr-id": "538",
    "commit-sha": "5f52655f5b61df71cca6343aa85e41e94088e056"
  },
  {
    "component": "enforcerd",
    "pr-id": "517",
    "commit-sha": "894cd49427b0313f141079ca04164d9a0f11a3b6"
  }
]
```

2018-03-20 23:01 UTC, varks commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "clad",
    "pr-id": "538",
    "commit-sha": "5f52655f5b61df71cca6343aa85e41e94088e056"
  },
  {
    "component": "enforcerd",
    "pr-id": "517",
    "commit-sha": "90cff365975bf4b239c8dc9e5146982f3a85e276"
  },
  {
    "component": "squall",
    "pr-id": "337",
    "commit-sha": "376512f27219d5dc7f1576206b046d6ae6c0a25a"
  },
  {
    "component": "apotests",
    "pr-id": "1311",
    "commit-sha": "9187d27ba245bfbef2bc6fc79b972a1a109fdd41"
  },
  {
    "component": "gaia",
    "pr-id": "118",
    "commit-sha": "e92f3849b53bc399304203ccdba37557937ea870"
  },
  {
    "component": "trireme-lib",
    "pr-id": "497",
    "commit-sha": "a167ffc2d435143bc5886496203bd61e810ab21c"
  }
]
```

2018-03-20 23:32 UTC, amitlimaye approved these changes

2018-03-21 00:05 UTC, varks commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "gaia",
    "pr-id": "118",
    "commit-sha": "e92f3849b53bc399304203ccdba37557937ea870"
  },
  {
    "component": "trireme-lib",
    "pr-id": "497",
    "commit-sha": "92625e1cb38bf80da29be1ad50085d30e3c1e323"
  },
  {
    "component": "clad",
    "pr-id": "538",
    "commit-sha": "5f52655f5b61df71cca6343aa85e41e94088e056"
  },
  {
    "component": "enforcerd",
    "pr-id": "517",
    "commit-sha": "90cff365975bf4b239c8dc9e5146982f3a85e276"
  },
  {
    "component": "squall",
    "pr-id": "337",
    "commit-sha": "376512f27219d5dc7f1576206b046d6ae6c0a25a"
  },
  {
    "component": "apotests",
    "pr-id": "1311",
    "commit-sha": "e2e9788f54d3f3452e1a3932a0eca019daa1c624"
  }
]
```

2018-03-21 14:37 UTC, dstiliadis requested changes

2018-03-21 14:37 UTC, dstiliadis commented on controller/pkg/pucontext/pucontext.go
> +
We only need to search for encrypt if the policy is accept. if there is no packetAction it will be reject in the end anyway.

2018-03-21 19:10 UTC, varks commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "apotests",
    "pr-id": "1311",
    "commit-sha": "113be476fdb163881fa0cefac46c709e10dbe84a"
  },
  {
    "component": "apoctl",
    "pr-id": "118",
    "commit-sha": "8b080cf001966e33765884c198ec50cc56f3c90a"
  },
  {
    "component": "gaia",
    "pr-id": "118",
    "commit-sha": "e92f3849b53bc399304203ccdba37557937ea870"
  },
  {
    "component": "trireme-lib",
    "pr-id": "497",
    "commit-sha": "92625e1cb38bf80da29be1ad50085d30e3c1e323"
  },
  {
    "component": "clad",
    "pr-id": "538",
    "commit-sha": "5f52655f5b61df71cca6343aa85e41e94088e056"
  },
  {
    "component": "enforcerd",
    "pr-id": "517",
    "commit-sha": "90cff365975bf4b239c8dc9e5146982f3a85e276"
  },
  {
    "component": "kube-squall",
    "pr-id": "142",
    "commit-sha": "0e53f8c6d62ef1d2237f6779e1ded03e092f9082"
  },
  {
    "component": "squall",
    "pr-id": "337",
    "commit-sha": "376512f27219d5dc7f1576206b046d6ae6c0a25a"
  }
]
```

2018-03-21 20:08 UTC, varks commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "kube-squall",
    "pr-id": "142",
    "commit-sha": "7b19b8301c999af29c6ca6d751169a801e455c0e"
  },
  {
    "component": "squall",
    "pr-id": "337",
    "commit-sha": "376512f27219d5dc7f1576206b046d6ae6c0a25a"
  },
  {
    "component": "apotests",
    "pr-id": "1311",
    "commit-sha": "113be476fdb163881fa0cefac46c709e10dbe84a"
  },
  {
    "component": "apoctl",
    "pr-id": "118",
    "commit-sha": "8b080cf001966e33765884c198ec50cc56f3c90a"
  },
  {
    "component": "gaia",
    "pr-id": "118",
    "commit-sha": "e92f3849b53bc399304203ccdba37557937ea870"
  },
  {
    "component": "trireme-lib",
    "pr-id": "497",
    "commit-sha": "92625e1cb38bf80da29be1ad50085d30e3c1e323"
  },
  {
    "component": "clad",
    "pr-id": "538",
    "commit-sha": "5f52655f5b61df71cca6343aa85e41e94088e056"
  },
  {
    "component": "enforcerd",
    "pr-id": "517",
    "commit-sha": "90cff365975bf4b239c8dc9e5146982f3a85e276"
  }
]
```

2018-03-21 23:05 UTC, varks commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "squall",
    "pr-id": "337",
    "commit-sha": "376512f27219d5dc7f1576206b046d6ae6c0a25a"
  },
  {
    "component": "apotests",
    "pr-id": "1311",
    "commit-sha": "b5386f04e2d1693052620f00963c2cd83992f14b"
  },
  {
    "component": "apoctl",
    "pr-id": "118",
    "commit-sha": "8b080cf001966e33765884c198ec50cc56f3c90a"
  },
  {
    "component": "gaia",
    "pr-id": "118",
    "commit-sha": "f0be89cd64137454203eb7ee280d609a68c61e65"
  },
  {
    "component": "trireme-lib",
    "pr-id": "497",
    "commit-sha": "08335596dad850c874e76967a68360e2696ed302"
  },
  {
    "component": "clad",
    "pr-id": "538",
    "commit-sha": "58c022c118d801a2fd61e858b3c6612700351b82"
  },
  {
    "component": "enforcerd",
    "pr-id": "517",
    "commit-sha": "f0e69497423cdf7d6044b9e9a7db38892d9cb1d6"
  },
  {
    "component": "kube-squall",
    "pr-id": "142",
    "commit-sha": "32628d0d9f2ff26e0c106f6290e460a910f4f81f"
  }
]
```

2018-03-21 23:46 UTC, varks commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "squall",
    "pr-id": "337",
    "commit-sha": "376512f27219d5dc7f1576206b046d6ae6c0a25a"
  },
  {
    "component": "apotests",
    "pr-id": "1311",
    "commit-sha": "b7fed7f285158a038bb5e44b776efdd3b7fbea4b"
  },
  {
    "component": "apoctl",
    "pr-id": "118",
    "commit-sha": "8b080cf001966e33765884c198ec50cc56f3c90a"
  },
  {
    "component": "gaia",
    "pr-id": "118",
    "commit-sha": "f0be89cd64137454203eb7ee280d609a68c61e65"
  },
  {
    "component": "trireme-lib",
    "pr-id": "497",
    "commit-sha": "c1db88ff8ec9ab0fd93e4583313643abfee079d1"
  },
  {
    "component": "clad",
    "pr-id": "538",
    "commit-sha": "58c022c118d801a2fd61e858b3c6612700351b82"
  },
  {
    "component": "enforcerd",
    "pr-id": "517",
    "commit-sha": "f0e69497423cdf7d6044b9e9a7db38892d9cb1d6"
  },
  {
    "component": "kube-squall",
    "pr-id": "142",
    "commit-sha": "32628d0d9f2ff26e0c106f6290e460a910f4f81f"
  }
]
```

2018-03-22 00:04 UTC, varks commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "squall",
    "pr-id": "337",
    "commit-sha": "376512f27219d5dc7f1576206b046d6ae6c0a25a"
  },
  {
    "component": "apotests",
    "pr-id": "1311",
    "commit-sha": "b7fed7f285158a038bb5e44b776efdd3b7fbea4b"
  },
  {
    "component": "apoctl",
    "pr-id": "118",
    "commit-sha": "8b080cf001966e33765884c198ec50cc56f3c90a"
  },
  {
    "component": "gaia",
    "pr-id": "118",
    "commit-sha": "f0be89cd64137454203eb7ee280d609a68c61e65"
  },
  {
    "component": "trireme-lib",
    "pr-id": "497",
    "commit-sha": "c1db88ff8ec9ab0fd93e4583313643abfee079d1"
  },
  {
    "component": "clad",
    "pr-id": "538",
    "commit-sha": "58c022c118d801a2fd61e858b3c6612700351b82"
  },
  {
    "component": "enforcerd",
    "pr-id": "517",
    "commit-sha": "f0e69497423cdf7d6044b9e9a7db38892d9cb1d6"
  },
  {
    "component": "kube-squall",
    "pr-id": "142",
    "commit-sha": "32628d0d9f2ff26e0c106f6290e460a910f4f81f"
  }
]
```

2018-03-22 04:37 UTC, dstiliadis approved these changes

2018-03-22 05:43 UTC, varks commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "apotests",
    "pr-id": "1311",
    "commit-sha": "2670c014b877a1d133c6c9783618869e4acd5d5a"
  },
  {
    "component": "apoctl",
    "pr-id": "118",
    "commit-sha": "8b080cf001966e33765884c198ec50cc56f3c90a"
  },
  {
    "component": "gaia",
    "pr-id": "118",
    "commit-sha": "f0be89cd64137454203eb7ee280d609a68c61e65"
  },
  {
    "component": "trireme-lib",
    "pr-id": "497",
    "commit-sha": "c1db88ff8ec9ab0fd93e4583313643abfee079d1"
  },
  {
    "component": "clad",
    "pr-id": "538",
    "commit-sha": "58c022c118d801a2fd61e858b3c6612700351b82"
  },
  {
    "component": "enforcerd",
    "pr-id": "517",
    "commit-sha": "d21f14454aed16e77882b95381fb3b3b1d568005"
  },
  {
    "component": "kube-squall",
    "pr-id": "142",
    "commit-sha": "ceb5674b5904ea0c0c1eea23b066d3855726293c"
  },
  {
    "component": "squall",
    "pr-id": "337",
    "commit-sha": "376512f27219d5dc7f1576206b046d6ae6c0a25a"
  }
]
```

2018-03-22 22:28 UTC, varks commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "clad",
    "pr-id": "538",
    "commit-sha": "58c022c118d801a2fd61e858b3c6612700351b82"
  },
  {
    "component": "enforcerd",
    "pr-id": "517",
    "commit-sha": "d21f14454aed16e77882b95381fb3b3b1d568005"
  },
  {
    "component": "kube-squall",
    "pr-id": "142",
    "commit-sha": "79bd05e33a5e002b73fe9cc44787019a99b5336e"
  },
  {
    "component": "squall",
    "pr-id": "337",
    "commit-sha": "376512f27219d5dc7f1576206b046d6ae6c0a25a"
  },
  {
    "component": "apotests",
    "pr-id": "1311",
    "commit-sha": "2670c014b877a1d133c6c9783618869e4acd5d5a"
  },
  {
    "component": "apoctl",
    "pr-id": "118",
    "commit-sha": "8b080cf001966e33765884c198ec50cc56f3c90a"
  },
  {
    "component": "gaia",
    "pr-id": "118",
    "commit-sha": "38b692184684c5fb9f098da53848bc146ee05e33"
  },
  {
    "component": "trireme-lib",
    "pr-id": "497",
    "commit-sha": "c1db88ff8ec9ab0fd93e4583313643abfee079d1"
  }
]
```

2018-03-22 23:09 UTC, varks commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "squall",
    "pr-id": "337",
    "commit-sha": "cc3bf008c78a7d201ef72ab24a20f7f49fdc8cf1"
  },
  {
    "component": "apotests",
    "pr-id": "1311",
    "commit-sha": "ead4fc4f60aa2728ffc601b86bfb86d68a791932"
  },
  {
    "component": "apoctl",
    "pr-id": "118",
    "commit-sha": "41a5ef7a72a06902f9677b7774068cccc6885421"
  },
  {
    "component": "trireme-lib",
    "pr-id": "497",
    "commit-sha": "c1db88ff8ec9ab0fd93e4583313643abfee079d1"
  },
  {
    "component": "clad",
    "pr-id": "538",
    "commit-sha": "e00ceb89a9119cde8561a6555da421276b767755"
  },
  {
    "component": "enforcerd",
    "pr-id": "517",
    "commit-sha": "141753b97a72695fedfb1323fa821ec764354836"
  },
  {
    "component": "kube-squall",
    "pr-id": "142",
    "commit-sha": "e899096b45bd11c7d12cfdbc15f1228164aaeee3"
  }
]
```

2018-03-22 23:17 UTC, varks commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "apotests",
    "pr-id": "1311",
    "commit-sha": "fe2db75bb9e1fec78fec78b16be02ba5bc73c78b"
  },
  {
    "component": "apoctl",
    "pr-id": "118",
    "commit-sha": "41a5ef7a72a06902f9677b7774068cccc6885421"
  },
  {
    "component": "trireme-lib",
    "pr-id": "497",
    "commit-sha": "c1db88ff8ec9ab0fd93e4583313643abfee079d1"
  },
  {
    "component": "clad",
    "pr-id": "538",
    "commit-sha": "e00ceb89a9119cde8561a6555da421276b767755"
  },
  {
    "component": "enforcerd",
    "pr-id": "517",
    "commit-sha": "141753b97a72695fedfb1323fa821ec764354836"
  },
  {
    "component": "kube-squall",
    "pr-id": "142",
    "commit-sha": "e899096b45bd11c7d12cfdbc15f1228164aaeee3"
  },
  {
    "component": "squall",
    "pr-id": "337",
    "commit-sha": "cc3bf008c78a7d201ef72ab24a20f7f49fdc8cf1"
  }
]
```

2018-03-23 00:42 UTC, varks commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "clad",
    "pr-id": "538",
    "commit-sha": "e00ceb89a9119cde8561a6555da421276b767755"
  },
  {
    "component": "enforcerd",
    "pr-id": "517",
    "commit-sha": "141753b97a72695fedfb1323fa821ec764354836"
  },
  {
    "component": "kube-squall",
    "pr-id": "142",
    "commit-sha": "e899096b45bd11c7d12cfdbc15f1228164aaeee3"
  },
  {
    "component": "squall",
    "pr-id": "337",
    "commit-sha": "d687d88e2f2055ee1666a039a76a5c2d12e60daf"
  },
  {
    "component": "apotests",
    "pr-id": "1311",
    "commit-sha": "fe2db75bb9e1fec78fec78b16be02ba5bc73c78b"
  },
  {
    "component": "apoctl",
    "pr-id": "118",
    "commit-sha": "41a5ef7a72a06902f9677b7774068cccc6885421"
  },
  {
    "component": "trireme-lib",
    "pr-id": "497",
    "commit-sha": "c1db88ff8ec9ab0fd93e4583313643abfee079d1"
  }
]
```

2018-03-23 01:01 UTC, varks commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "squall",
    "pr-id": "337",
    "commit-sha": "d687d88e2f2055ee1666a039a76a5c2d12e60daf"
  },
  {
    "component": "apotests",
    "pr-id": "1311",
    "commit-sha": "fe2db75bb9e1fec78fec78b16be02ba5bc73c78b"
  },
  {
    "component": "apoctl",
    "pr-id": "118",
    "commit-sha": "41a5ef7a72a06902f9677b7774068cccc6885421"
  },
  {
    "component": "trireme-lib",
    "pr-id": "497",
    "commit-sha": "c1db88ff8ec9ab0fd93e4583313643abfee079d1"
  },
  {
    "component": "clad",
    "pr-id": "538",
    "commit-sha": "e00ceb89a9119cde8561a6555da421276b767755"
  },
  {
    "component": "enforcerd",
    "pr-id": "517",
    "commit-sha": "2a5b2bbbb6fb4cfebdc729273de3d4203ea6aaf6"
  },
  {
    "component": "kube-squall",
    "pr-id": "142",
    "commit-sha": "e899096b45bd11c7d12cfdbc15f1228164aaeee3"
  }
]
```

2018-03-23 16:18 UTC, varks commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "apotests",
    "pr-id": "1311",
    "commit-sha": "55d9d2e5a186dcdc4c61cbf15ce764d3f070914c"
  },
  {
    "component": "apoctl",
    "pr-id": "118",
    "commit-sha": "41a5ef7a72a06902f9677b7774068cccc6885421"
  },
  {
    "component": "trireme-lib",
    "pr-id": "497",
    "commit-sha": "c1db88ff8ec9ab0fd93e4583313643abfee079d1"
  },
  {
    "component": "clad",
    "pr-id": "538",
    "commit-sha": "e00ceb89a9119cde8561a6555da421276b767755"
  },
  {
    "component": "enforcerd",
    "pr-id": "517",
    "commit-sha": "2a5b2bbbb6fb4cfebdc729273de3d4203ea6aaf6"
  },
  {
    "component": "kube-squall",
    "pr-id": "142",
    "commit-sha": "e899096b45bd11c7d12cfdbc15f1228164aaeee3"
  },
  {
    "component": "squall",
    "pr-id": "337",
    "commit-sha": "d687d88e2f2055ee1666a039a76a5c2d12e60daf"
  }
]
```

2018-03-23 18:21 UTC, varks commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "apotests",
    "pr-id": "1311",
    "commit-sha": "55d9d2e5a186dcdc4c61cbf15ce764d3f070914c"
  },
  {
    "component": "apoctl",
    "pr-id": "118",
    "commit-sha": "41a5ef7a72a06902f9677b7774068cccc6885421"
  },
  {
    "component": "trireme-lib",
    "pr-id": "497",
    "commit-sha": "c1db88ff8ec9ab0fd93e4583313643abfee079d1"
  },
  {
    "component": "vince",
    "pr-id": "84",
    "commit-sha": "3ae8f743023eda285900faf9881a5b5213768d2b"
  },
  {
    "component": "clad",
    "pr-id": "538",
    "commit-sha": "e00ceb89a9119cde8561a6555da421276b767755"
  },
  {
    "component": "enforcerd",
    "pr-id": "517",
    "commit-sha": "2a5b2bbbb6fb4cfebdc729273de3d4203ea6aaf6"
  },
  {
    "component": "kube-squall",
    "pr-id": "142",
    "commit-sha": "e899096b45bd11c7d12cfdbc15f1228164aaeee3"
  },
  {
    "component": "squall",
    "pr-id": "337",
    "commit-sha": "d687d88e2f2055ee1666a039a76a5c2d12e60daf"
  }
]
```

2018-03-23 23:41 UTC, merged