adding l4proto in flowrecord
aporeto-inc/trireme-lib pull request #499
Opened 2018-03-27 18:35 UTC by 0xmchadha

#### Description
Add l4 protocol in the flow reported
#### Test plan

> Fixes #.

2018-03-28 03:36 UTC, t00f commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "jenova",
    "pr-id": "8",
    "commit-sha": "ce0b235cc0624ea2a21b141db2ca26852275f62e"
  },
  {
    "component": "gaia",
    "pr-id": "121",
    "commit-sha": "2e3c03df94394278a7fcf4b24b6f512c2caad0b1"
  },
  {
    "component": "clad",
    "pr-id": "549",
    "commit-sha": "2772718cbf4e3bb3a16ac7f394ac4d84aff64108"
  },
  {
    "component": "trireme-lib",
    "pr-id": "499",
    "commit-sha": "c2652d9c16de82b7c2a46ee742c177ab4650ac34"
  },
  {
    "component": "enforcerd",
    "pr-id": "532",
    "commit-sha": "5d478f5f931c6aab3b516f390520c29185746196"
  }
]
```

2018-03-28 19:57 UTC, t00f commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "gaia",
    "pr-id": "121",
    "commit-sha": "21a2cdba6a6d448d3e96c6bd1f5db3baa2f89373"
  },
  {
    "component": "clad",
    "pr-id": "549",
    "commit-sha": "2772718cbf4e3bb3a16ac7f394ac4d84aff64108"
  },
  {
    "component": "trireme-lib",
    "pr-id": "499",
    "commit-sha": "c2652d9c16de82b7c2a46ee742c177ab4650ac34"
  },
  {
    "component": "enforcerd",
    "pr-id": "532",
    "commit-sha": "5d478f5f931c6aab3b516f390520c29185746196"
  },
  {
    "component": "jenova",
    "pr-id": "8",
    "commit-sha": "b4266a8fb19281a4f274af01d955d580864df46f"
  }
]
```

2018-03-28 20:02 UTC, t00f requested changes

2018-03-28 20:02 UTC, t00f commented on collector/interfaces.go
> +	L4Proto          uint8
Can we rename internal variables with complete names to make it clear ?
Use `L4Protocol` instead of `L4Proto`

2018-03-28 20:24 UTC, t00f approved these changes

2018-03-28 20:54 UTC, dstiliadis commented on controller/internal/enforcer/applicationproxy/tcp/tcp.go
> +	Packet "github.com/aporeto-inc/trireme-lib/controller/pkg/packet"
No capital names in package names.

2018-03-29 20:17 UTC, t00f commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "gaia",
    "pr-id": "121",
    "commit-sha": "c38b8870d6afbd3cefb13766bbb89a0b2ccfad30"
  },
  {
    "component": "clad",
    "pr-id": "549",
    "commit-sha": "2772718cbf4e3bb3a16ac7f394ac4d84aff64108"
  },
  {
    "component": "trireme-lib",
    "pr-id": "499",
    "commit-sha": "e6680c0951b75468fb85ccd7922cada078283228"
  },
  {
    "component": "enforcerd",
    "pr-id": "532",
    "commit-sha": "9e33f845175c7f11bce9ff0a9f2ca483761bcb55"
  },
  {
    "component": "jenova",
    "pr-id": "8",
    "commit-sha": "a71cca0c0bfec99dfeeed4d24b30a187d59f60b6"
  }
]
```

2018-03-29 21:11 UTC, t00f commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "trireme-lib",
    "pr-id": "499",
    "commit-sha": "e3fa8aed6c16195973d5dfbb57119420a6c23901"
  },
  {
    "component": "enforcerd",
    "pr-id": "532",
    "commit-sha": "9e33f845175c7f11bce9ff0a9f2ca483761bcb55"
  },
  {
    "component": "gaia",
    "pr-id": "121",
    "commit-sha": "c38b8870d6afbd3cefb13766bbb89a0b2ccfad30"
  }
]
```

2018-04-02 18:07 UTC, t00f commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "component": "trireme-lib",
    "pr-id": "499",
    "commit-sha": "a9309dde0c71b29efab3697d8bb6bb4a272af28e"
  },
  {
    "component": "enforcerd",
    "pr-id": "532",
    "commit-sha": "096a5ed1b1496aa6caeaccb3aee177d4c45c6a9a"
  },
  {
    "component": "gaia",
    "pr-id": "121",
    "commit-sha": "fbeeed0b16005cf6bf19e7fe5ffa2dcfc254c65a"
  }
]
```

2018-04-02 22:48 UTC, merged