Use ACL cache to resolve udp external services
aporeto-inc/trireme-lib pull request #564
Opened 2018-08-01 18:34 UTC by varks

2018-08-01 20:42 UTC, amitlimaye approved these changes

2018-08-02 15:01 UTC, dstiliadis commented on controller/internal/enforcer/nfqdatapath/datapath_udp.go
> +
Can't we just check the protocol and call one of the above, rather than both?

2018-08-02 15:02 UTC, dstiliadis commented on controller/internal/enforcer/nfqdatapath/datapath_udp.go
> +
Don't we know the direction? I can see this creating problems if I use 0.0.0.0. Why check for both directions?

2018-08-02 15:04 UTC, dstiliadis requested changes
See above for some suggestions.

2018-08-02 20:55 UTC, dstiliadis approved these changes

2018-08-02 22:35 UTC, merged